### ISSUE TITLE
In production Release failed - env variable not importing

### ISSUE THREAD

**Issue by 2manoj1** [goatandsheep/react-native-dotenv#38] opened 2020-07-30 17:12 UTC
On Production build ios React Native 0.63.2 build failed. From `@env` variable not importing.

**Comment by goatandsheep** [comment] 2020-07-30 17:27
What is the error? What does your `.babelrc` look like?

**Comment by goatandsheep** [comment] 2020-07-30 17:44
If this is your project https://github.com/2manoj1/breactnative/blob/master/babel.config.js , make sure to add the module to your list of babel plugins

https://github.com/goatandsheep/react-native-dotenv/wiki/Migration-Guide#2

**Comment by 2manoj1** [comment] 2020-07-30 18:42
```
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset'
  ],
  env: {
    production: {},
  },
  plugins: [
    [
      '@babel/plugin-proposal-decorators',
      {
        legacy: true,
      },
    ],
    ['@babel/plugin-proposal-optional-catch-binding'],
    ["module:react-native-dotenv", {
      "moduleName": "@env",
      "path": ".env",
      "blacklist": null,
      "whitelist": null,
      "safe": false,
      "allowUndefined": false
    }]
  ],
```
@goatandsheep Its my config. Its running development mode but in production build its failed.

**Comment by goatandsheep** [comment] 2020-08-03 17:09
Related to https://github.com/tusbar/babel-plugin-dotenv-import/issues/164

**Comment by oleksandr-dziuban** [comment] 2020-08-06 11:46
@goatandsheep Same for me, all production builds failed
``SyntaxError: /Users/oleksandr_dziuban/Projects/ELAT-DEV/mobile-web-app/ios/src/core/env.js: "RAYGUN_API_KEY" is not defined in .env``

**Comment by AndriyF** [comment] 2020-08-06 12:49
@oleksandr-dziuban Dirty workaround to fix failed builds in my case was to set `allowUndefined: true` in a babel config file.

**Comment by goatandsheep** [comment] 2020-08-06 13:08
@AndriyF do you think `allowUndefined: true` should be set as default?

**Comment by AndriyF** [comment] 2020-08-06 14:04
@goatandsheep there are no restrictions set by default, soI think for the sake for consistency it's better to have `allowUndefined: true`

**Comment by goatandsheep** [comment] 2020-08-06 15:23
I've changed the default for `v2.3.0`. For the rest of the issues, I've [placed a bounty for $15](https://www.bountysource.com/issues/92243570-in-production-release-failed-env-variable-not-importing)

**Comment by 2manoj1** [comment] 2020-08-06 17:07
@goatandsheep check this. In code two dotenv config. can you check this. 
<img width="507" alt="Screenshot 2020-08-06 at 10 32 36 PM" src="https://user-images.githubusercontent.com/15128569/89560707-1119ef00-d835-11ea-90f4-3a813a839ebf.png">

**Comment by goatandsheep** [comment] 2020-08-06 17:53
@2manoj1 that isn't it. The `dotenv` creators suggest it here: ( https://github.com/motdotla/dotenv/issues/390#issuecomment-487214696 ). Also, the issue is also present in the original fork https://github.com/goatandsheep/react-native-dotenv/issues/38#issuecomment-668137017

**Comment by goatandsheep** [comment] 2020-08-12 13:32
@2manoj1 is this also affecting dev builds like ticket #52

**Comment by 2manoj1** [comment] 2020-08-12 15:36
No. In Dev build it was worked as expected.

**Comment by goatandsheep** [comment] 2020-08-12 18:47
I think I know what the issue is. I'll address it this weekend.

**Comment by BurakKartal1** [comment] 2020-08-25 13:24
for those that has empty variables in release builds. just change ur env like this -->

from
`API_URL=YOUR_API_URL`

to
`API_URL='YOUR_API_URL'`

**Comment by goatandsheep** [comment] 2020-08-25 13:47
@BurakKartal1 huh. that's interesting. I wonder why that works. Should the library cast the values to strings?

**Comment by MrtYlnzz** [comment] 2020-08-26 20:08
I am having same issue on 0.63.2 any update on this?

**Comment by info-bit** [comment] 2020-08-31 12:48
I'm having the same problem (react-native is 0.63.2), but nothing of the above worked for me. I can build in debug, but not in production.

**Comment by goatandsheep** [comment] 2020-08-31 21:20
Can you try again with the new release and let me know if that works?

**Comment by MrtYlnzz** [comment] 2020-09-01 08:13
@goatandsheep I have tested on 2.4.0 and it seems to have not solved the issue for me.

**Comment by goatandsheep** [comment] 2020-09-01 11:31
@MrtYlnzz thank you for checking

**Comment by chmiiller** [comment] 2020-09-09 19:48
Hi there, thanks for supporting this package. 
For me it is working fine on development but I can confirm that **it is not working on release mode** on iOS - I didn't test on Android.
I've just created a react-native project using CRA. My "babel.config.js" file looks like this (I don't know what a "babelrc" file is)

```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    ["module:react-native-dotenv"]
  ],
};
```

I'm using:
react: 16.13.1
react-native: 0.63.2
react-native-dotenv: 2.4.0

node v10.20.1
Xcode 11.4.1

Looking forward for a fix =)

**Comment by oalcantarpcore** [comment] 2020-09-10 22:38
Hi there, thank you for this amazing package :)

I'm having this issue too, in development mode it works perfectly but it fails in release mode (i'm using xCode)... 

I changed in my `babel.config.js` the key `allowUndefined` to `true` and the build works but I think it only prevents throw the error because my code is not taking the values from the '.env` file.

I'm using:
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-dotenv": "^2.2.0",

**Comment by Slals** [comment] 2020-09-20 23:52
Hi, any news on this issue?

xCode build get error `is not defined in .env` when building release, it works in debug mode. I use multi-env and tried to create a `.env` (I use `.env.production` in normal condition).

"react-native": "0.63.2",
"react-native-dotenv": "^2.4.0",

**Comment by Slals** [comment] 2020-09-21 02:40
I found a quick workaround, it seems xcode doesn't resolve the path from the project directory source but from `ios/`, and it is looking for a `.env` in this directory.

So just `cp .env ios/` or `cp .env.production ios/` will allow you to build.

Note that the error triggered by `react-native-dotenv` will block the building of the `main.jsbundle` file. This issue can be related to https://github.com/facebook/react-native/issues/18472 for some people.

**Comment by hung-nb** [comment] 2020-09-21 05:46
"react-native": "0.63.2",
"react-native-dotenv": "^2.4.0"

iOS - debug build is good
but iOS - release build doesn't work.

As @Slals said, "cp .env ios", then it works.

Waiting for new build for "react-native-dotenv"

Thanks @goatandsheep for this good package :)

**Comment by alizahid** [comment] 2020-09-21 13:48
I played around with the file names for a bit and here's what I found;

For iOS release, `.env` is treated as `.env.production`.
For iOS debug, `.env.development` works.

**Comment by rhoberman** [comment] 2020-10-10 17:54
+1 for @Slals workaround. Same setup as @hung-nb.

**Comment by ahmadmahomed** [comment] 2020-10-20 12:11
I can confirm the the same issue is present on an Android release build and _undefined_  gets generated within the release bundle. 

The workaround suggested by @Slals works for an iOS release build.

**Comment by davidprovan** [comment] 2020-11-17 16:18
We fixed this issue our our build by referencing this:

https://github.com/facebook/react-native/issues/29351#issuecomment-657929014

Hopefully helps someone else stumbles onto this thread.  H/T to Matt Burnett on our team for finding it.

**Comment by eridr** [comment] 2020-11-20 21:23
In my case it was all about giving xcode full access to the hard drive.
Select System Preferences->Security & Privacy->Full Disk Access 
then + and add xcode

**Comment by jack828** [comment] 2020-12-20 11:32
Has anyone tried setting BABEL_ENV before building? I was experiencing this for android release builds:
`BABEL_ENV=production ./gradlew assembleRelease`

I added some logging to this package and found that first time it is run BABEL_ENV is correctly set, then it is set to `"undefined"` and tries to load `.env.undefined` instead of the correct mode.

```
// console.log in react-native-dotenv/index.js pre() function
 { BABEL_ENV: 'production',
   typeBABEL_ENV: 'string',
   NODE_ENV: 'production',
   typeNODE_ENV: 'string' }
 .env
 { ...output of my .env... }
 .env.production
 { ...output of my .env.production }


 { BABEL_ENV: 'undefined',
   typeBABEL_ENV: 'string',
   NODE_ENV: 'production',
   typeNODE_ENV: 'string' }
 .env
 { ...output of my .env... }
 react-native-dotenv { Error: ENOENT: no such file or directory, open '.env.undefined'


```

**Comment by goatandsheep** [comment] 2020-12-20 14:14
@jack828 I've never seen that one but we surely can prevent it.

**Comment by goatandsheep** [comment] 2021-01-20 13:52
Some people are saying to follow the Android signing guide before building to prod https://reactnative.dev/docs/signed-apk-android#adding-signing-config-to-your-apps-gradle-config

**Comment by goatandsheep** [comment] 2021-01-26 14:55
@jack828 i reread your comment. And it absolutely by design uses the BABEL_ENV name that you want. I recommend you read the readme and Wiki

**Comment by jack828** [comment] 2021-01-26 15:22
@goatandsheep Sure. I did read both in trying to fix this issue.

I also lost a lot of time trying to fix this for iOS builds and ended up having to add `BABEL_ENV=production` to all of my build commands and in the xcode build script.

I don't mean to be rude but it's not exactly helpful when I (and many others) have followed the wiki and migration guides and are still experiencing this issue - I'm hazarding a guess at that there is some misconfiguration somewhere (in this package or otherwise) that is incorrectly setting `BABEL_ENV` to `"undefined"`, which is the root cause for this issue.

I've provided you with a location where we can start looking for a potential fix - even something as simple as a check `BABEL_ENV === "undefined"` falling back to (valid) `NODE_ENV`, as per what your wiki says?
```
The variables will automatically be pulled from the appropriate environment and development is the default. 
The choice of environment is based on your Babel environment first and if it can't find that your
NPM environment, which should actually be the same, but if the Babel environment
isn't set it uses the NPM environment for robustness.
```

I think the `"undefined"` check is a simple and reasonable addition as who is going to genuinely use `.env.undefined`?

**Comment by goatandsheep** [comment] 2021-01-26 15:26
sure! I'll add an undefined check. If you have an idea, you're welcome to make a pull request.

**Comment by jack828** [comment] 2021-01-26 15:29
@goatandsheep Thanks, I appreciate that!

Just to be clear, it is not strictly undefined, but a string `"undefined"` - if I have time this week and get to it before you do I will see what I can do!

**Comment by goatandsheep** [comment] 2021-01-26 15:48
@jack828 no worries. fix is in and published!

**Comment by ivanichi** [comment] 2021-02-02 01:17
i'm having the same problem on release android, env undefined, any news on this issue ? 

react native 0.63.3
dotenv 2.5.0

**Comment by backlands** [comment] 2021-02-02 01:24
> @jack828 no worries. fix is in and published as v2.5.1

As noted the 2.5.1 release should help you @ivanichi

**Comment by ivanichi** [comment] 2021-02-02 12:51
> > @jack828 no worries. fix is in and published as v2.5.1
> 
> As noted the 2.5.1 release should help you @ivanichi

thank you. it works

**Comment by zhahaoyu** [comment] 2021-02-21 07:45
I am still having the issue for ios
"react-native": "0.63.2"
"react-native-dotenv": "^2.5.3"

**Comment by zhahaoyu** [comment] 2021-02-21 08:05
If I move `.env` and `.env.production` to ios folder, then the problem is solved.

**Comment by ivanichi** [comment] 2021-02-22 15:39
today i have issue, react native 0.63.3, dotenv 2.5.3, 
I have ENVFILE=.env.xxx everything is working, assembleDebug, assembleRelease. ( it works ) 
and then bundleRelease. Testing the release build : 
`$ react-native run-android --variant=release` ( fails to pick up env.xxx )
any suggestions or updates for this ?

**Comment by goatandsheep** [comment] 2021-02-22 19:08
Hi @ivanichi this library is not checking for `ENVFILE` to my knowledge. Also `release` should be `<path from babel config>.production`. Multi-env is inspired by [dotenv-flow](https://www.npmjs.com/package/dotenv-flow). You can also book me to take a look at your project to make some suggestions https://issuehunt.io/r/goatandsheep/react-native-dotenv/issues/38

I'd also recommend if there are missing values that you clear the cache: `yarn start --reset-cache`

**Comment by zhahaoyu** [comment] 2021-02-22 19:18
@goatandsheep will there be a fix so we don't need to copy the .env files to the ios folder?

**Comment by goatandsheep** [comment] 2021-02-22 20:03
Hm...do you think this is a simple path fix? I'm not having this issue on my end, so I will not release until fully tested, but can you test the following branch?

```json

  "devDependencies": {
    "react-native-dotenv": "git+https://git@github.com/goatandsheep/react-native-dotenv.git#bugfix/gh-38"
  }
```

**Comment by ivanichi** [comment] 2021-02-23 09:37
@goatandsheep thank you for your suggestions and reply, I will try to explore, if successful i will come back, if on my case doesn't work I'll be happy to contact via the link above

**Comment by ivanichi** [comment] 2021-02-23 16:42
> today i have issue, react native 0.63.3, dotenv 2.5.3,
> I have ENVFILE=.env.xxx everything is working, assembleDebug, assembleRelease. ( it works )
> and then bundleRelease. Testing the release build :
> `$ react-native run-android --variant=release` ( fails to pick up env.xxx )
> any suggestions or updates for this ?

now `react-native run-android --variant=release` success to pick up env.xxx
I experimented until felt like a mummy, thank you this library is very useful 
for my case i changed : `process.env.BABEL_ENV `to `process.env.ENVFILE`

`yarn start --reset-cache`
`cd android && ./gradlew clean` 
`wipe data avd emulator`
`restart the computer` 

and build again, the problem has been resolved

react native 0.63.3, dotenv 2.5.3,

**Comment by goatandsheep** [comment] 2021-02-23 16:54
I'm happy it works for you! Please leave a tip if possible https://issuehunt.io/r/goatandsheep/react-native-dotenv/issues/38

I wish cache cleaning were easier. Maybe this? https://www.npmjs.com/package/react-native-clean-project

**Comment by ivanichi** [comment] 2021-02-23 17:14
> I'm happy it works for you! Please leave a tip if possible https://issuehunt.io/r/goatandsheep/react-native-dotenv/issues/38
> 
> I wish cache cleaning were easier. Maybe this? https://www.npmjs.com/package/react-native-clean-project

of course with pleasure. I want to send a donation via paypal. please give me your paypal email, thank you.

**Comment by goatandsheep** [comment] 2021-02-23 17:16
https://paypal.me/kemalahmedmac

**Comment by gabrieljoelc** [comment] 2021-03-30 16:52
@ivanichi

we've had the issue of needing to restart the computer when changing values in the `.env`.

does anyone know why you have to restart the computer?

**Comment by goatandsheep** [comment] 2021-03-30 16:55
It's a caching issue. I'll be doing a bit of maintenance tomorrow 😊

**Comment by ivanichi** [comment] 2021-04-01 16:08
@gabrieljoelc  yes, it should be clean. and you need a cup of coffee for a bit. so need a restart. 
if you can't to pick up .env after restart. try for run : `export BABEL_ENV = .yourenv`

**Comment by gabrieljoelc** [comment] 2021-04-01 16:48
@ivanichi thanks.

Yes the restarts have consistently worked but it's pretty painful when switching between environments for test and prod builds

**Comment by alizahid** [comment] 2021-04-03 19:01
I'm able to get this working reliably by having two `env` files; `.env.development` and `.env.production` as specified in the docs and not having `.env` at all.

**Comment by goatandsheep** [comment] 2021-04-06 19:54
The solution is now to install https://www.npmjs.com/package/react-native-clean-project and clean using that. No more restarts.

**Comment by gabrieljoelc** [comment] 2021-04-12 18:08
@alizahid doh! i'm on an old version that doesn't have those niceties. I'll bump in the next version of the app

@goatandsheep what's the `react-native-clean-project` command you use to clear the cache?

**Closed** 2021-06-18 21:37 UTC
Labels: wontfix

**Comment by brianwachira** [comment] 2022-10-24 12:19
> The solution is now to install https://www.npmjs.com/package/react-native-clean-project and clean using that. No more restarts.

I have tried this on React Native v0.70.3 and it is not working.
I have 2 .env files, `.env.development` and `.env.production`
Here is my babel.config.js

`module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        moduleName: '@env',
        path: '.env',
        blacklist: null,
        whitelist: null,
        safe: false,
        allowUndefined: true,
      },
    ],
    'react-native-reanimated/plugin',
  ],
};
`

I have tried all the solutions above and none of them work. I am considering to use another .env package. 
@goatandsheep please help?

**Comment by goatandsheep** [comment] 2022-10-26 01:50
Hi @brianwachira , I'm happy to help but what is the issue? What platform are you building to? Have you created your release / dev profiles on xcode/AS? Is this part of this ticket? This one has been closed for some time and probably should have been locked

**Comment by brianwachira** [comment] 2022-10-26 08:33
> Hi @brianwachira , I'm happy to help but what is the issue? What platform are you building to? Have you created your release / dev profiles on xcode/AS? Is this part of this ticket? This one has been closed for some time and probably should have been locked

Hi @goatandsheep , I am building to Android. So it turns out that the reason my `API_URL`  in .env was not recognized is that it is a `HTTP` & not `HTTPS` hence couldn't run on production because On android, as of API Level 28, clear text traffic is also blocked by default. I fixed the issue by setting [android:usesCleartextTraffic](https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic) in the app manifest file.

**Comment by Lauro235** [comment] 2022-11-04 02:06
Hi, there, I'm having an issue with my variables, showing as undefined.
Here is my babel.config.js
```
module.exports = function(api) {
  api.cache(true);
  return {
    "presets": ['babel-preset-expo', "module:react-native-dotenv"],
    "plugins": [
      [
        "module:react-native-dotenv", {
        "envName": "APP_ENV",
        "moduleName": "@env",
        "path": ".env",
        "allowUndefined": true,
        }
      ]
    ] 
  };
};
```
Currently using Node 18.12.0 and NPM 8.19.2

**Comment by goatandsheep** [comment] 2022-11-04 02:37
Try `cache(false)`?

**Comment by Lauro235** [comment] 2022-11-04 03:05
No Luck so far. I've tried clearing all the node modules and removing cache. It's not having it :(

**Comment by Lauro235** [comment] 2022-11-04 03:13
Somehow I fixed it.. For me this worked..

```
module.exports = function(api) {
  api.cache(false);
  return {
    presets: ['babel-preset-expo', "module:metro-react-native-babel-preset"],
    plugins: [
      [
        "module:react-native-dotenv", {
        "envName": "APP_ENV",
        "moduleName": "@env",
        "path": ".env",
        }
      ]
    ] 
  };
};
```
```
  "dependencies": {
    "@expo/webpack-config": "^0.16.19",
    "expo": "~46.0.16",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-auth0": "^2.14.1",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "metro-react-native-babel-preset": "^0.73.3",
    "react-native-dotenv": "^3.3.1"
  },
  ```

**Comment by odera89** [comment] 2023-11-27 18:24
> @goatandsheep will there be a fix so we don't need to copy the .env files to the ios folder?

I have the same issue.
