### ISSUE TITLE
.env file variables are cached

### ISSUE THREAD

**Issue by mvehar** [goatandsheep/react-native-dotenv#75] opened 2020-09-28 09:27 UTC
.env changes are not propagated to code.

If you update .env, new values will not be detected until you change the file that imports the variables.

**Comment by goatandsheep** [comment] 2020-09-28 13:52
are you re-building between `.env` changes?

**Comment by mvehar** [comment] 2020-09-28 13:58
I'm using react-native run-ios, which reloads the code. Could be that babel modules are not reloaded until some code ts/js code changes.

**Comment by goatandsheep** [comment] 2020-09-28 14:34
yeah unfortunately, you'll have to fully restart the script every time you change your `.env` file

**Comment by proIT324** [comment] 2020-09-28 17:08
I run `react-native run-ios` whenever I modify `.env` file. However, old environment variables are cached and leveraged again. What should I do to reset them?

**Comment by goatandsheep** [comment] 2020-09-28 18:15
Oh! I think I know what's wrong. This is [one of the caveats about this package](https://github.com/goatandsheep/react-native-dotenv#caveats). For now, try this and let me know if that fixes it:

```shell
rm -rf node_modules/.cache/babel-loader/*
```

I also want to see if we can observe changes and clear the cache going forward like in this other babel plugin https://github.com/codemix/babel-plugin-closure-elimination/blob/master/src/index.js

**Comment by proIT324** [comment] 2020-09-28 18:17
@goatandsheep Thank you! It eventually resolved the issue. Could you update the package?

**Comment by goatandsheep** [comment] 2020-09-28 18:18
It will take time for me to figure it out. I'll update the security dependencies, but this feature will have to wait until next month unless someone can help me.

**Comment by SebinLee** [comment] 2020-09-29 04:15
> Oh! I think I know what's wrong. This is [one of the caveats about this package](https://github.com/goatandsheep/react-native-dotenv#caveats). For now, try this and let me know if that fixes it:
> 
> ```shell
> rm -rf node_modules/.cache/babel-loader/*
> ```
> 
> I also want to see if we can observe changes and clear the cache going forward like in this other babel plugin https://github.com/codemix/babel-plugin-closure-elimination/blob/master/src/index.js

I have same problem, but It cannot solve my problem
I also cleared watchman, metro module cache, but nothing changes.
Both on android, iOS environment

**Comment by mvehar** [comment] 2020-10-01 14:52
Maybe a temp solution for updating package.json scripts:

>     "cc": "rimraf node_modules/.cache/babel-loader/*,",
>     "android": "npm run cc && react-native run-android",
>     "ios": "npm run cc && react-native run-ios",

**Comment by TJTorola** [comment] 2020-10-06 14:47
Repost from https://github.com/zetachang/react-native-dotenv/issues/70, after a lot of digging, I think this https://github.com/babel/babel/issues/8497 is really what react-native-dotenv needs to get this fixed. Seeing as there is currently no way to tell babel that the .env file is a dependency requiring a new build react-native-dotenv cannot possibly get it to rebuild when the env file changes.

I think I have a partial workaround though, changing metro.config.js to include:

```javascript
const crypto = require('crypto');
const fs = require('fs');

let hash = crypto.createHash('sha256');
hash.update(fs.readFileSync('.env'));
const cacheVersion = hash.digest('hex');

module.exports = { // eslint-disable-line import/no-commonjs
  ...
  cacheVersion,
};
```
See: https://facebook.github.io/metro/docs/configuration#cacheversion

This results in metro using the hash of the .env file as a cache key and therefore invalidates the cache when the env file changes. I don't believe this will work for live reloading, you would still need to restart react-native whenever the env or any files using it changes, but we've been running with this for some time and haven't had anymore env caching issues.

This is particularly pressing for us because our CI agents build JS bundles for 3 different enviornments in an unpredictable order so any env caching between those could cause a production outage for us. But thankfully we haven't seen that for the last few months since doing this change.

**Comment by TJTorola** [comment] 2020-10-06 14:54
Looks like https://github.com/babel/babel/pull/11741 might provide a proper solution here also?

**Comment by bhailot** [comment] 2020-10-08 12:20
when I ran "rm -rf node_modules/.cache/babel-loader/*", got module not found error. I do not see .cache folder inside node_modules

**Comment by Definence** [comment] 2020-10-22 10:45
Same issue. `rm -rf node_modules/.cache/babel-loader/*` does not seem to help

**Comment by kingdavidmartins** [comment] 2020-11-02 15:03
@TJTorola https://github.com/zetachang/react-native-dotenv/issues/70#issuecomment-645559873
I have experienced this issue a couple of times.I know this doesn't solve the underlying issue with pertaining to live re loads

But when you cp or update your .env with new values before running your code push command you can pass the `--extra-bundler-option="--reset-cache"` flag

Example

```
appcenter codepush release-react -a ${app} --mandatory true -t ${version} --output-dir ./build --deployment-name ${deployment} --extra-bundler-option="--reset-cache"
```

after env swaps the new `env` values should be picked up when you codepush

**Comment by TJTorola** [comment] 2020-11-02 15:12
@kingdavidmartins Yeah, that works as well. My goal with hashing the `.env` file is that it does basically that, but automatically. Though, when doing a appcenter release it's probably best to ditch the cache every single time just to be safe like you have there.

**Comment by goatandsheep** [comment] 2020-11-02 21:51
@TJTorola anything we can do to the library to automatically do this? I'm happy to accept any PRs. I really want to resolve this.

**Comment by TJTorola** [comment] 2020-11-03 14:48
@goatandsheep I'm not sure, I don't think it can be properly fixed without https://github.com/babel/babel/pull/11741 getting patched first.

**Comment by perroudsky** [comment] 2020-11-16 13:54
for expo users,
`expo r -c`
did the job !

**Comment by hatemalimam** [comment] 2020-11-20 08:58
this should help
`yarn start --reset-cache`

**Comment by mvehar** [comment] 2021-05-21 10:00
Another approach with embeding the reset unto run-* commands
Android: 
`extraPackagerArgs: ["--reset-cache", ...], 
`
inside app/build.gradle

IOS:
Edit scheme->Run-> add 
EXTRA_PACKAGER_ARGS='--reset-cache' under ENV variables.

**Comment by taylorkline** [comment] 2021-07-06 20:54
@goatandsheep I think this issue should be re-opened, and perhaps even pinned. This is not an issue with `babel-loader` so the caveat currently in the README does not address this issue (I do not have `babel-loader` in my `yarn.lock` nor do I have the `node_modules/.cache` directory). 

This issue can be reproduced by init'ing a new React Native project with:

`npx react-native init MyApp --template react-native-template-typescript`

And then adding this dependency. Until `yarn start --reset-cache` is provided, no environmental variables appear within the app, and no changes are reflected until the cache is reset again.

**Comment by goatandsheep** [comment] 2021-07-06 21:16
@taylorkline HM... Sorry to hear about the continuing issues. What do you recommend we do? React native uses babel. If you have issues and it's not using babel loader but it's solved with this other yarn command that is also included in the readme, then isn't it solved? How can I help?

**Comment by taylorkline** [comment] 2021-07-07 17:05
> If you have issues and it's not using babel loader but it's solved with this other yarn command that is also included in the readme, then isn't it solved?

Ah, I see. I had a misunderstanding.

As it's currently written, the caveats section sounds like it only applies specifically to people who might have manually added a babel caching solution.

Since this issue of caching applies to the majority of users, including anyone who adds this project to a new React Native project, I would really suggest adding something like:

"You must clean the babel cache after each change to your environmental variables using `yarn start --reset-cache` or, if using expo, `expo r -c`."

up more prominently within the `Usage` section of the README.

Thanks for hearing me @goatandsheep

**Comment by goatandsheep** [comment] 2021-07-07 23:01
That's good feedback 👍 I'll try to improve the readme to clarify

**Comment by cgallivanpam** [comment] 2021-09-21 23:13
I have tried everything from `expo r -c` to yarn start `--reset-cache`. I think at the end of the day it may require a computer restart... thanks @goatandsheep for working on a solution. I see you all accross the forums working on this. 🙏

**Comment by Akshh057** [comment] 2021-11-24 12:31
yarn start --reset-cache works for me!

**Comment by seba9999** [comment] 2021-11-26 09:38
Using expo ``expo r -c`` works ... But as I have to change often of environnements... It's annoyingly long ! :'( 

Deleting the `node_modules/.cache/babel-loader/` solution seems to be a more effective way ... But I can't find any '.cache' folder in my nodes_modules :(

 I din't try the @TJTorola's solution yet ... But seems overcomplicated ...
> I think I have a partial workaround though, changing metro.config.js to include:

**Comment by TJTorola** [comment] 2021-11-29 16:08
@goatandsheep It looks like https://github.com/babel/babel/pull/11741 got approved a few days ago. Maybe something to keep an eye on since with that API we could properly fix this problem.

**Comment by goatandsheep** [comment] 2021-11-29 16:13
@TJTorola I've been checking it every day. I never thought that would happen but since it seems it will happen I will reopen this ticket

**Comment by andidev** [comment] 2021-11-30 12:28
Not sure if this helps but setting `resetCache: true` in metre.config.js makes cache reset everytime metro starts (anyway you it gets started).

![olipaysdk-app – metro config js 2021-11-30 13-24-53](https://user-images.githubusercontent.com/571389/144047280-af56805b-c91a-482b-90af-501ce387d94f.png)

**Comment by nisargrthakkar** [comment] 2022-01-07 18:06
@goatandsheep Please try ```resetCache: true``` in metro.config.js as per @andidev  answer its work for me.

Thanks @andidev

**Comment by phankietit** [comment] 2022-01-09 12:11
My solution 😂:

Package.json file:
```
"start:dev": "APP_ENV=dev npx react-native start --reset-cache",
"start:staging": "APP_ENV=staging npx react-native start --reset-cache",
"start:prod": "APP_ENV=prod npx react-native start --reset-cache",
```

**Comment by lkdm** [comment] 2022-01-20 00:19
What a stupid issue. And nothing I've tried in this thread has been able to fix it.

**Comment by goatandsheep** [comment] 2022-01-20 05:12
@lkdm This issue has been reopened as a placeholder to maintainers awaiting babel updates but if the readme is insufficient please provide more information

**Comment by lkdm** [comment] 2022-01-20 05:17
@goatandsheep I was able to solve it by `rm -rf`ìng the entire repository and pulling from remote.

**Comment by goatandsheep** [comment] 2022-01-20 11:56
That will do it but you'll have to figure out a solution that works every time you change your dotenv values. For now i recommend adding the babel cache false but when this is merged in you won't have to

**Comment by nisargrthakkar** [comment] 2022-01-21 05:40
resetCache: true is working for me

**Comment by goatandsheep** [comment] 2022-02-02 17:25
changes from the babel PR are merged! Time to implement this when the next babel release comes out: https://github.com/babel/babel/pull/14065#issuecomment-1009334079

**Comment by goatandsheep** [comment] 2022-02-14 04:36
if people can help review the incoming PR #288 , that will help tremendously. I will publish it under a `next` tag to it after I get review

**Comment by goatandsheep** [comment] 2022-03-20 17:31
please test the next version https://www.npmjs.com/package/react-native-dotenv/v/3.4.0 if I get 3 thumbs up from the post I'll publish this as the proper change

**Comment by GoaGit** [comment] 2022-03-22 10:16
@goatandsheep I've tested `v3.4.0` and experience the following issue (using `Expo` and `v3.3.1` of `react-native-dotenv` this particular issue does not occur). I haven't changed anything, other that installing the `v3.4.0` version of `react-native-dotenv`.

I will look into this in more detail, but perhaps you can spot the issue right away.

```
C:/Users/USER/AppData/Roaming/npm/node_modules/expo-cli/node_modules/react-dev-utils/webpackHotDevClient.js
Module build failed (from C:/Users/USER/AppData/Roaming/npm/node_modules/expo-cli/node_modules/babel-loader/lib/index.js):
TypeError: [BABEL] C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\node_modules\react-dev-utils\webpackHotDevClient.js: api.addExternalDependency is not a function (While processing: "Z:\\Connected.Football\\monorepo\\mobile-app\\node_modules\\react-native-dotenv\\index.js")
    at module.exports (Z:\Connected.Football\monorepo\mobile-app\node_modules\react-native-dotenv\index.js:105:7)
    at C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@babel\core\lib\config\full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@babel\core\lib\gensync-utils\async.js:26:3)
    at Generator.next (<anonymous>)
    at step (C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\node_modules\gensync\index.js:261:32)
    at evaluateAsync (C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\node_modules\gensync\index.js:291:5)
    at Function.errback (C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\node_modules\gensync\index.js:113:7)
    at errback (C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@babel\core\lib\gensync-utils\async.js:70:18)
    at async (C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\node_modules\gensync\index.js:188:17)
    at onFirstPause (C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\node_modules\gensync\index.js:216:13)
    at Generator.next (<anonymous>)
    at cachedFunction (C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@babel\core\lib\config\caching.js:68:46)
    at cachedFunction.next (<anonymous>)
    at loadPluginDescriptor (C:\Users\USER\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@babel\core\lib\config\full.js:235:43)
    at loadPluginDescriptor.next (<anonymous>)
```

**Comment by TJTorola** [comment] 2022-03-22 15:06
@goatandsheep I'll try and take a look at that version sometime this or next week.

**Comment by wcastand** [comment] 2022-03-23 14:03
Tested on 3.4.0 and the env are not updated without `--clear` still.
i have a `ROOT_API` in  `.env`
and one in `.env.staging`

and switching between both this doesn't change the `ROOT_API` unless i do `--clear` :)

```
    "start": "NODE_ENV=development expo start",
    "start:staging": "NODE_ENV=staging expo start",
```

**Comment by cbroome** [comment] 2022-03-23 21:38
I'm seeing this behavior when using typescript/tsc any idea of how to reliably delete the cache?

**Comment by alequint8912** [comment] 2022-05-25 16:06
> this should help `yarn start --reset-cache`
> 
> Possibile duplicate: [zetachang/react-native-dotenv#24](https://github.com/zetachang/react-native-dotenv/issues/24)

Thanks thats work for me!!

**Comment by danteyc** [comment] 2022-06-02 03:56
> this should help `yarn start --reset-cache`
> 
> Possibile duplicate: [zetachang/react-native-dotenv#24](https://github.com/zetachang/react-native-dotenv/issues/24)

Thanks. Thats work for me

**Comment by liuyankit** [comment] 2022-06-22 16:47
Nothing mentioned above seems to work for my expo project mixed up with react web stuffs

**Comment by himgodfreyho** [comment] 2022-08-08 07:10
None of the above solutions worked for me, and finally this works: https://github.com/zetachang/react-native-dotenv/issues/24#issuecomment-581125204. And this is super annoying as if I have 10 files using the environment variable, I have to change all the files...

**Comment by XAMEUS** [comment] 2022-08-08 13:59
None of the above solution worked for me, but I just found the cached files and removed them.

First, to search where was the cached files (with expo, but you might be able to find them elsewhere without it) :
```
grep . -rne "API_URL"
```
I then found it in `.expo/web/cache/development/babel-loader/481dd7b81fe573de380af60e33e4c7b2.json`.
Therefore to regenerate it, I just cleaned it (and restart the app):
```
rm -rf .expo/web/cache
```

**Comment by himgodfreyho** [comment] 2022-08-08 14:43
> None of the above solution worked for me, but I just found the cached files and removed them.
> 
> First, to search where was the cached files (with expo, but you might be able to find them elsewhere without it) :
> 
> ```
> grep . -rne "API_URL"
> ```
> 
> I then found it in `.expo/web/cache/development/babel-loader/481dd7b81fe573de380af60e33e4c7b2.json`. Therefore to regenerate it, I just cleaned it (and restart the app):
> 
> ```
> rm -rf .expo/web/cache
> ```

Man you save my day!!!! This works thanks.

**Comment by alessandrogelmi** [comment] 2022-10-25 08:07
I'm still having the same problem

**Comment by Michael-Davison** [comment] 2022-10-28 15:28
still having issues on expo 45. Have tried every solution in here.

**Comment by haotang-dayone** [comment] 2022-11-01 12:17
Tried all solutions above and none worked for me.

This nuke worked.
`rm -rf node_module && npm i`

Cheers!

**Comment by haotangio** [comment] 2022-11-01 12:18
Tried all solutions above and none worked for me.

This nuke worked.
rm -rf node_module && npm i

Cheers!

**Comment by shafayeatsumit** [comment] 2022-11-03 09:25
The problem lies in  `node_modules/react-native-config/ios/ReactNativeConfig/GeneratedDotEnv.m` this file is not reflecting the changes you made in your `.env` file.

**Closed** 2022-11-03 17:37 UTC
Labels: bug

**Comment by goatandsheep** [comment] 2023-03-02 12:21
Hi @esphung issues specific to that environment no longer exist. Please open a new ticket explaining your setup
