### ISSUE TITLE
api.addExternalDependency is not a function

### ISSUE THREAD

**Issue by dk253** [goatandsheep/react-native-dotenv#377] opened 2022-11-09 21:29 UTC
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%247%20Funded-%2300A156.svg" />](https://issuehunt.io/r/goatandsheep/react-native-dotenv/issues/377)

After more than a year, I am now getting an error when I run $NODE_ENV=development expo start --web

The error is: 
Uncaught Error: Module build failed (from ./node_modules/@expo/webpack-config/node_modules/babel-loader/lib/index.js):
TypeError: [BABEL] ./node_modules/@expo/webpack-config/node_modules/react-dev-utils/webpackHotDevClient.js: api.addExternalDependency is not a function

**To Reproduce**
This is my babel.config.js:
```
module.exports = (api) => {
    api.cache(true);
    return {
        presets: ['babel-preset-expo'],
        plugins: [
            ['module:react-native-dotenv'],
            'react-native-reanimated/plugin',
        ]
    };
}
```
my dependencies:
```
  "dependencies": {
    "@apollo/client": "^3.6.0-beta.5",
    "@expo-google-fonts/lato": "^0.2.2",
    "@expo/config-plugins": "^5.0.0",
    "@expo/dev-server": "^0.1.123",
    "@expo/match-media": "^0.3.0",
    "@formatjs/intl-datetimeformat": "^4.5.1",
    "@formatjs/intl-displaynames": "^5.4.1",
    "@formatjs/intl-getcanonicallocales": "^1.9.0",
    "@formatjs/intl-listformat": "^6.5.1",
    "@formatjs/intl-locale": "^2.4.44",
    "@formatjs/intl-numberformat": "^7.4.1",
    "@formatjs/intl-pluralrules": "^4.3.1",
    "@formatjs/intl-relativetimeformat": "^9.5.1",
    "@mdi/js": "^6.9.96",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@react-navigation/stack": "^6.1.1",
    "@stripe/react-stripe-js": "^1.10.0",
    "@stripe/stripe-js": "^1.34.0",
    "@stripe/stripe-react-native": "0.19.0",
    "@types/react": "^18.0.20",
    "@types/react-native": "~0.70.6",
    "apollo-link": "^1.2.14",
    "apollo-link-error": "^1.1.13",
    "apollo-link-timeout": "^4.0.0",
    "apollo-upload-client": "^16.0.0",
    "async": "^3.2.4",
    "async-csv": "^2.1.3",
    "async-json2csv": "^1.0.4",
    "base-64": "^1.0.0",
    "csv": "^6.2.0",
    "deprecated-react-native-prop-types": "^2.3.0",
    "detox-expo-helpers": "^0.6.0",
    "dotenv": "^16.0.3",
    "eas-cli": "^2.3.0",
    "emoji-picker-react": "^4.4.4",
    "expo": "~47.0.3",
    "expo-application": "~5.0.1",
    "expo-asset": "~8.6.1",
    "expo-constants": "~14.0.2",
    "expo-credit-card": "^0.0.5",
    "expo-dev-client": "~2.0.0",
    "expo-device": "~5.0.0",
    "expo-document-picker": "~11.0.1",
    "expo-file-system": "~15.1.1",
    "expo-font": "~11.0.1",
    "expo-intent-launcher": "~10.3.0",
    "expo-linking": "~3.2.2",
    "expo-localization": "~14.0.0",
    "expo-modules-core": "~1.0.2",
    "expo-notifications": "~0.17.0",
    "expo-screen-orientation": "~5.0.1",
    "expo-secure-store": "~12.0.0",
    "expo-sharing": "~11.0.1",
    "expo-splash-screen": "~0.17.4",
    "expo-status-bar": "~1.4.2",
    "expo-updates": "~0.15.4",
    "expo-web-browser": "~12.0.0",
    "file-saver": "^2.0.5",
    "firebase": "^9.6.10",
    "graphql": "^15.5.1",
    "graphql-tag": "^2.12.5",
    "graphql-ws": "^5.6.4",
    "jest": "^26.6.3",
    "lodash": "^4.17.21",
    "metro-config": "^0.67.0",
    "moment": "^2.29.3",
    "parsecurrency": "^1.0.1",
    "patch-package": "^6.4.7",
    "postinstall-postinstall": "^2.1.0",
    "prop-types": "^15.7.2",
    "react": "18.1.0",
    "react-apollo-network-status": "^5.1.0",
    "react-currency-format": "^1.1.0",
    "react-dev-utils": "^12.0.1",
    "react-devtools-core": "^4.26.0",
    "react-dom": "18.1.0",
    "react-error-overlay": "^6.0.11",
    "react-hook-form": "^7.10.1",
    "react-moment": "^1.1.1",
    "react-native": "0.70.5",
    "react-native-animation-library": "^0.0.8",
    "react-native-app-link": "^1.0.1",
    "react-native-autocomplete-dropdown": "^1.1.5",
    "react-native-emoji-selector": "^0.2.0",
    "react-native-error-boundary": "^1.1.12",
    "react-native-flash-message": "^0.1.23",
    "react-native-format-currency": "^0.0.3",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-get-random-values": "^1.8.0",
    "react-native-global-state-hooks": "^1.1.6",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-hyperlink": "^0.0.22",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-mime-types": "^2.3.0",
    "react-native-pager-view": "6.0.1",
    "react-native-paper": "^4.12.1",
    "react-native-paper-dates": "^0.4.6",
    "react-native-paper-dropdown": "^1.0.7",
    "react-native-paper-form-builder": "^2.1.2",
    "react-native-paper-tabs": "^0.7.0",
    "react-native-ratings": "^8.1.0",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "13.4.0",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "~0.18.7",
    "react-responsive": "^9.0.0-beta.6",
    "react-usestateref": "^1.0.8",
    "rn-emoji-keyboard": "^0.7.1",
    "sentry-expo": "^5.0.3",
    "standard-version": "^9.5.0",
    "standard-version-expo": "^1.0.3",
    "uuidv4": "^6.2.13"
  },
  "devDependencies": {
    "@babel/core": "^7.20.2",
    "@babel/eslint-parser": "^7.19.1",
    "@expo/ngrok": "^4.1.0",
    "@expo/webpack-config": "~0.16.21",
    "@graphql-eslint/eslint-plugin": "^3.7.0",
    "@react-native-community/eslint-config": "^3.0.1",
    "babel-eslint": "^10.1.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-transform-inline-environment-variables": "^0.4.4",
    "babel-preset-expo": "^9.2.2",
    "detox": "^18.20.0",
    "enzyme": "^3.11.0",
    "eslint": "^8.11.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-plugin-detox": "^1.0.0",
    "eslint-plugin-flowtype": "8.0.3",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-react-hooks": "^4.3.0",
    "eslint-plugin-react-native": "^4.0.0",
    "expo-detox-hook": "*",
    "jest-circus": "^27.0.6",
    "jest-expo": "^45.0.0",
    "prettier": "^2.5.1",
    "react-native-testing-library": "^6.0.0",
    "react-test-renderer": "17",
    "selenium-webdriver": "^4.4.0"
  },
```

**Expected behavior**
To add my environment variables from my .env file.

**Desktop (please complete the following information):**
 - OS: mac osx 13.0
 - Browser firefox and chrome

**Additional context**
I have cleared my cache, as other articles have suggested.  But no love.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $7.00)

- [<img src='https://avatars.githubusercontent.com/u/6131657?v=4' alt='dk253' width=24 height=24> dk253](https://issuehunt.io/u/dk253) ($5.00)
- [<img src='https://avatars.githubusercontent.com/u/51499934?v=4' alt='joseph-the-dreamer' width=24 height=24> joseph-the-dreamer](https://issuehunt.io/u/joseph-the-dreamer) ($2.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/goatandsheep/react-native-dotenv/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by goatandsheep** [comment] 2022-11-09 21:49
This is a good bug. The issue is that I did not update dependency version minimum for Babel. This is a brand new feature i worked on with the Babel team to eliminate pesky caching issues. Let me look into it

**Comment by goatandsheep** [comment] 2022-11-09 21:50
May i rename this ticket "api.addExternalDependency is not a function"?

**Comment by dk253** [comment] 2022-11-09 21:55
@goatandsheep of course.  Thanks!

**Comment by dk253** [comment] 2022-11-09 22:47
@goatandsheep woohoo!  That did it on my local machine.  Now I'll test with github actions.

**Comment by dk253** [comment] 2022-11-09 23:17
Huge!  Spent a long time tracking this.  Thanks for your answer.  Works all the way through.

**Comment by goatandsheep** [comment] 2022-12-01 01:22
Huh. Maybe metro also needs to be updated.

**Comment by joseph-the-dreamer** [comment] 2022-12-01 17:27
I'm running into the same issue. I tried updating the package.json with the specified versions from @goatandsheep and @christopherbauer. No luck. Still getting the `api.addExternalDependency is not a function` error

**Comment by goatandsheep** [comment] 2022-12-01 17:45
I will create experimental version today that forces the specific babel version

**Comment by christopherbauer** [comment] 2022-12-01 17:45
> I'm running into the same issue. I tried updating the package.json with the specified versions from @goatandsheep and @christopherbauer. No luck. Still getting the `api.addExternalDependency is not a function` error

I only changed package.json and am installing with --legacy-peer-deps, I would not necessarily recommend that but there's a bunch of conflicts between native-base, react-dom and react-native that has me temporarily using it so that might be an avenue.

**Comment by goatandsheep** [comment] 2022-12-01 17:50
do you think I should set them as peer deps?

```json
  "peerDependencies": {
    "@babel/core": "^7.20.2",
    "babel-loader": "^8.3.0"
  }
```

**Comment by christopherbauer** [comment] 2022-12-01 18:10
> do you think I should set them as peer deps?
> 
> ```json
>   "peerDependencies": {
>     "@babel/core": "^7.20.2",
>     "babel-loader": "^8.3.0"
>   }
> ```
> 
> I will experiment later this evening when I have time but if someone can confirm, I can push out a test without experimenting on expo / metro / etc.

I'm not an expert but that appears correct - whatever the earliest version of babel to feature api.addExternalDependency (and up) would clear this up for people who pull the next release. Of note - I installed 7.20.1 of the @babel/runtime, not v8. That's a major version increase and might introduce dependency hell for some poor soul who stumbles across it so I'd seek the closest versions if you have the time.

Being that the babel version fix worked for me on metro and I initialized the react-native project earlier this month I'm fairly confident that it would be accurate for newer versions of react-native. However it bears repeating that I'm utilizing --legacy-peer-deps so I might not be the best sample for the fix.

**Comment by goatandsheep** [comment] 2022-12-01 19:06
HM... those were the versions recommended by the Babel maintainers I worked with on this feature. This library is one of the first to use this feature. when this is all resolved I'll contribute what was learned to other Babel/ dotenv libs.

I'll try the 7.x.x version today and if we still have concerns/issues in testing I might have to do the 8.x later🤞

**Comment by goatandsheep** [comment] 2022-12-03 15:32
okay I read something wrong. I mentioned `babel-loader` should be v8 and you said `babel-runtime`. I'll set `babel-runtime to v7.20.5 just in case there's anything weird there

**Comment by goatandsheep** [comment] 2022-12-05 09:14
I have been testing things all weekend to get this fix out but because the versions don't use ~ or ^ and yarn hasn't implemented override, I cannot do it from the library side. I did a lot of research.

I will try however to keep pestering the expo team to merge the current pr

**Comment by koaladlt** [comment] 2023-01-20 00:01
Hello! Any update on this?

**Comment by goatandsheep** [comment] 2023-01-20 01:24
Until https://github.com/expo/expo-cli/pull/4593 is merged, you'll have to use the workaround above. If you can ping the reviewers that would help speed things up

**Comment by ajyang818** [comment] 2023-01-22 21:21
First off - appreciate how you're actively maintaining this repo! 

What is the recommended workaround that you mention, until the Expo change is widely available? I've tried adding this to `package.json`:
```
"peerDependencies": {
    "@babel/core": "^7.20.2",
    "babel-loader": "^8.3.0"
  }
```
And also tried specifying `@babel/runtime: "7.20.6"` there as well, along with trying a `rm -rf node_modules/` followed by having yarn reinstall everything, and a `npx expo start -c` to boot. But, still getting the `api.addExternalDependency is not a function` error when attempting to access my app on web.

**Comment by ajyang818** [comment] 2023-01-22 21:40
Naturally, as soon as I post the question, my continued finagling seems to have gotten things to work :)

In case it helps others, I kept finagling my app to look closer and closer to the expo example provided here: https://github.com/goatandsheep/react-native-dotenv-expo-test

The more notable things I did, but unclear which solved the issue:
- Instead of adding the `peerDependencies` section to my `package.json`, I changed that heading to `resolutions`
- I moved react-native-dotenv from a dependency to a devDependency
- The `plugins` array for my `babel.config.js` looks like this:
```
        plugins: [
            [
                'module:react-native-dotenv',
                {
                  moduleName: 'react-native-dotenv',
                  verbose: true,
                },
              ],
        ],
```
- And in a file, I'm importing via `import { BACKEND_SERVER_URL } from "react-native-dotenv"` and just using `BACKEND_SERVER_URL` plain, as if it were a variable, in the code. Note that VSCode is complaining that the module has no exported member called `BACKEND_SERVER_URL`, but it all works in the end.

(Thank you @goatandsheep for that Expo example repo!)

**Comment by goatandsheep** [comment] 2023-03-24 13:35
Given that the PR for expo was merged, this deserves a re-test, but the ticket will likely be closed.

**Comment by YarmanDev** [comment] 2023-03-24 14:09
> Given that the PR for expo was merged, this deserves a re-test, but the ticket will likely be closed.

Seems like the issue still produces. But interesting point, that it is producing in Github Actions, locally everything works fine.
I have tried to follow @ajyang818 recomendation steps, but no luck so far.

Here is my `package.json`: 

```
"resolutions": {
    "@babel/core": "^7.20.2",
    "babel-loader": "8.3.0",
  },

"dependencies": {
    "@expo/webpack-config": "^0.17.2",
    "expo": "^47.0.0",
    "expo-web-browser": "~12.0.0",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-web": "~0.18.7",
  }

"devDependencies": {
    "babel-loader": "^8.3.0",
    "react-native-dotenv": "^3.4.8",
  },

```

And `babel.config.js`: 
```
module.exports = function (api) {
    api.cache(false)

    return {
        presets: ['babel-preset-expo'],
        plugins: [
            '@babel/plugin-proposal-nullish-coalescing-operator',
            'react-native-reanimated/plugin',
            [
                'module:react-native-dotenv',
                {
                    moduleName: 'react-native-dotenv',
                    verbose: true,
                },
            ],
        ],
    }
}

```

**Comment by goatandsheep** [comment] 2023-03-24 14:17
I guess we also have to wait for the next release before we can use the changes too 😅

**Closed** 2023-06-18 11:32 UTC
Labels: wontfix, :dollar: Funded on Issuehunt
